<?php
ob_start();
error_reporting(0);
ini_set('display_errors', 0);

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

require_once __DIR__ . '/../../../includes/database.php';

if (!isset($_SESSION['user_id'])) {
    die('Unauthorized');
}

$user_id = $_SESSION['user_id'];
$type = isset($_GET['type']) ? $_GET['type'] : 'weekly';
$start_date = isset($_GET['start_date']) ? $_GET['start_date'] : date('Y-m-d', strtotime('monday this week'));
$end_date = isset($_GET['end_date']) ? $_GET['end_date'] : date('Y-m-d');

// Get user name
$user_query = "SELECT CONCAT(first_name, ' ', last_name) as name FROM users WHERE user_id = $user_id";
$user_result = mysqli_query($connection, $user_query);
$user_name = mysqli_fetch_assoc($user_result)['name'];

// Get activities
$activities_query = "SELECT * FROM employee_activities WHERE employee_id = $user_id AND activity_date BETWEEN '$start_date' AND '$end_date' ORDER BY activity_date";
$activities_result = mysqli_query($connection, $activities_query);

// Get tasks
$tasks_query = "SELECT t.*, c.company_name FROM employee_tasks t 
                JOIN clients c ON t.client_id = c.client_id 
                WHERE t.employee_id = $user_id 
                AND (t.date_started BETWEEN '$start_date' AND '$end_date' 
                OR t.updated_at BETWEEN '$start_date' AND '$end_date')
                ORDER BY t.updated_at DESC";
$tasks_result = mysqli_query($connection, $tasks_query);

// Get expenses
$expenses_query = "SELECT * FROM employee_expenses 
                   WHERE employee_id = $user_id 
                   AND expense_date BETWEEN '$start_date' AND '$end_date'
                   ORDER BY expense_date DESC";
$expenses_result = mysqli_query($connection, $expenses_query);

$filename = "Activity_Report_" . str_replace(' ', '_', $user_name) . "_" . date('Y-m-d') . ".xls";
header("Content-Type: application/vnd.ms-excel");
header("Content-Disposition: attachment; filename=\"$filename\"");

echo "<html><body>";
echo "<table border='1' cellpadding='5' cellspacing='0'>";

// Header
echo "<tr style='background:#0a2240; color:#f1bf70;'>";
echo "<td colspan='6'><h2 style='margin:0;'>Activity Report</h2></td>";
echo "</tr>";
echo "<tr><td colspan='2'><b>Employee Name:</b> " . htmlspecialchars($user_name) . "</td><td colspan='2'><b>Employee ID:</b> " . htmlspecialchars($user_id) . "</td><td colspan='2'><b>Report Generated By:</b> System</td></tr>";
echo "<tr><td colspan='6'><b>Period:</b> " . date('M d, Y', strtotime($start_date)) . " - " . date('M d, Y', strtotime($end_date)) . "</td></tr>";
echo "<tr><td colspan='6'>&nbsp;</td></tr>";

// Summary Stats
$total_hours = 0;
mysqli_data_seek($activities_result, 0);
while($act = mysqli_fetch_assoc($activities_result)) {
    $total_hours += $act['hours_worked'];
}
mysqli_data_seek($activities_result, 0);

$total_tasks = mysqli_num_rows($tasks_result);
$total_expenses = 0;
mysqli_data_seek($expenses_result, 0);
while($exp = mysqli_fetch_assoc($expenses_result)) {
    $total_expenses += $exp['amount'];
}
mysqli_data_seek($expenses_result, 0);

echo "<tr style='background:#f5f5f5;'>";
echo "<td colspan='2'><b>Total Hours:</b> " . $total_hours . " hrs</td>";
echo "<td colspan='2'><b>Total Tasks:</b> " . $total_tasks . "</td>";
echo "<td colspan='2'><b>Total Expenses:</b> AED " . number_format($total_expenses, 2) . "</td>";
echo "</tr>";
echo "<tr><td colspan='6'>&nbsp;</td></tr>";

// Daily Activities Section
echo "<tr style='background:#667eea; color:white;'>";
echo "<th colspan='6'>DAILY ACTIVITIES</th>";
echo "</tr>";
echo "<tr style='background:#e9ecef;'>";
echo "<th>Date</th><th>Day</th><th>Hours</th><th>Clients</th><th>Location</th><th>Nature of Work</th>";
echo "</tr>";

if(mysqli_num_rows($activities_result) > 0) {
    while($act = mysqli_fetch_assoc($activities_result)) {
        echo "<tr>";
        echo "<td>" . date('M d, Y', strtotime($act['activity_date'])) . "</td>";
        echo "<td>" . date('l', strtotime($act['activity_date'])) . "</td>";
        echo "<td>" . $act['hours_worked'] . "</td>";
        echo "<td>" . htmlspecialchars($act['clients_attended'] ?: '-') . "</td>";
        echo "<td>" . htmlspecialchars($act['work_location']) . "</td>";
        echo "<td>" . nl2br(htmlspecialchars($act['nature_of_work'])) . "</td>";
        echo "</tr>";
    }
} else {
    echo "<tr><td colspan='6' align='center'>No activities recorded in this period</td></tr>";
}

echo "<tr><td colspan='6'>&nbsp;</td></tr>";

// Tasks Section
echo "<tr style='background:#667eea; color:white;'>";
echo "<th colspan='6'>TASKS</th>";
echo "</tr>";
echo "<tr style='background:#e9ecef;'>";
echo "<th>Client</th><th>Job Type</th><th>Status</th><th>Date Started</th><th>Est. Completion</th><th>Remarks</th>";
echo "</tr>";

if(mysqli_num_rows($tasks_result) > 0) {
    while($task = mysqli_fetch_assoc($tasks_result)) {
        $status_color = '';
        if($task['status'] == 'Completed') $status_color = '#28a745';
        elseif($task['status'] == 'Work in progress') $status_color = '#0d6efd';
        elseif($task['status'] == 'Pending') $status_color = '#ffc107';
        else $status_color = '#6c757d';
        
        echo "<tr>";
        echo "<td>" . htmlspecialchars($task['company_name']) . "</td>";
        echo "<td>" . htmlspecialchars($task['job_type'] ?: '-') . "</td>";
        echo "<td style='color:" . $status_color . "; font-weight:bold;'>" . htmlspecialchars($task['status']) . "</td>";
        echo "<td>" . ($task['date_started'] ? date('M d, Y', strtotime($task['date_started'])) : '-') . "</td>";
        echo "<td>" . ($task['estimated_completion_date'] ? date('M d, Y', strtotime($task['estimated_completion_date'])) : '-') . "</td>";
        echo "<td>" . nl2br(htmlspecialchars($task['remarks'] ?: '-')) . "</td>";
        echo "</tr>";
    }
} else {
    echo "<tr><td colspan='6' align='center'>No tasks in this period</td></tr>";
}

echo "<tr><td colspan='6'>&nbsp;</td></tr>";

// Expenses Section
echo "<tr style='background:#667eea; color:white;'>";
echo "<th colspan='6'>EXPENSES</th>";
echo "</tr>";
echo "<tr style='background:#e9ecef;'>";
echo "<th>Date</th><th>Client</th><th>Type</th><th>Mode</th><th>Amount</th><th>Description</th>";
echo "</tr>";

if(mysqli_num_rows($expenses_result) > 0) {
    while($exp = mysqli_fetch_assoc($expenses_result)) {
        $client_name = '';
        if($exp['client_id']) {
            $client_q = "SELECT company_name FROM clients WHERE client_id = " . $exp['client_id'];
            $client_r = mysqli_query($connection, $client_q);
            if($client_r && mysqli_num_rows($client_r) > 0) {
                $client_name = mysqli_fetch_assoc($client_r)['company_name'];
            }
        } else {
            $client_name = $exp['client_name'] ?: '-';
        }
        
        echo "<tr>";
        echo "<td>" . date('M d, Y', strtotime($exp['expense_date'])) . "</td>";
        echo "<td>" . htmlspecialchars($client_name) . "</td>";
        echo "<td>" . htmlspecialchars($exp['expense_type']) . "</td>";
        echo "<td>" . htmlspecialchars($exp['mode_of_transport'] ?: '-') . "</td>";
        echo "<td>AED " . number_format($exp['amount'], 2) . "</td>";
        echo "<td>" . nl2br(htmlspecialchars($exp['description'] ?: '-')) . "</td>";
        echo "</tr>";
    }
} else {
    echo "<tr><td colspan='6' align='center'>No expenses recorded in this period</td></tr>";
}

echo "<tr><td colspan='6'>&nbsp;</td></tr>";
echo "<tr><td colspan='6' align='center'><i>Report generated on " . date('M d, Y H:i:s') . "</i></td></tr>";
echo "</table>";
echo "</body></html>";

ob_end_flush();
?>